export const GET_EXPENSE_GROUPS_URL = "http://localhost:5289/api/expensegroup"
export const GET_EXPENSES_URL = "http://localhost:5289/api/expense"
export const GET_USERS_URL = "http://localhost:5289/api/user"
export const GET_PERCENTAGES_URL = "http://localhost:5289/api/percentages"
export const GET_GROUP_MEMBERS_URL = "http://localhost:5289/api/groupmembers"
export const LOGIN_URL = "http://localhost:5289/api/account/login"
export const REGISTER_URL = "http://localhost:5289/api/account/register"